// Text of the staff admin area (Step 17). English only; staff-facing.

export const admin = {
  name: "Kinzoku admin",
  nav: { requests: "Requests", staff: "Staff", account: "My account", logout: "Log out" },

  login: {
    title: "Staff login",
    email: "Email",
    password: "Password",
    submit: "Log in",
    sending: "Logging in…",
    wrong: "Wrong email or password, or the account is switched off.",
    tooMany: "Too many attempts. Please wait 15 minutes and try again.",
    failed: "Login is not available right now. Please try again.",
  },

  requests: {
    title: "Requests",
    all: "All",
    search: "Search reference, company, name or email",
    searchButton: "Search",
    empty: "No requests found.",
    columns: { reference: "Reference", received: "Received", company: "Company", contact: "Contact", type: "Request", status: "Status", files: "Files" },
    previous: "Previous",
    next: "Next",
    page: (page: number, pages: number) => `Page ${page} of ${pages}`,
  },

  request: {
    back: "All requests",
    received: (date: string) => `Received ${date}`,
    moveTo: "Move to:",
    answers: "Answers",
    files: "Files",
    noFiles: "No files attached.",
    download: "Download",
    history: "Status history",
    arrived: "Request arrived",
    by: (name: string) => `by ${name}`,
    byDeleted: "by a former staff member",
    emails: "Emails",
    emailKinds: { buyer_confirmation: "Confirmation to the buyer", sales_alert: "Alert to the sales team" },
    emailSent: (date: string) => `sent ${date}`,
    emailWaiting: (attempts: number) => (attempts ? `not sent yet (${attempts} attempts)` : "waiting to be sent"),
    client: "Client",
    clientLinked: (name: string, since: string) => `${name}, client since ${since}. Kept 7 years.`,
    notClient: "Not linked to a client: deleted 12 months after it arrived, as the Privacy Policy says.",
    markClient: "Mark as client",
    company: { name: "Company name", country: "Country", vat: "VAT number (optional)", since: "Client since", submit: "Link as client" },
  },

  staff: {
    title: "Staff",
    add: "Add a staff member",
    name: "Name",
    email: "Email",
    role: "Role",
    roles: { admin: "Admin (also manages staff)", sales: "Sales" },
    submit: "Add",
    created: (email: string) => `Account made for ${email}. Give them this temporary password (shown only now); they choose their own at the first login:`,
    exists: "This email already has an account.",
    columns: { name: "Name", email: "Email", role: "Role", lastLogin: "Last login", status: "Status" },
    never: "never",
    active: "Active",
    off: "Switched off",
    you: "you",
    resetPassword: "New temporary password",
    newPassword: "New temporary password (shown only now):",
    endSessions: "Log out everywhere",
    sessionsEnded: "Logged out on all devices.",
    switchOff: "Switch off",
    switchOn: "Switch on",
    notYourself: "You can't do this to your own account.",
  },

  account: {
    title: "My account",
    mustChange: "Please choose your own password before you continue.",
    current: "Current password",
    new: "New password",
    newHint: "At least 12 characters. A few unrelated words make a strong password.",
    confirm: "New password again",
    submit: "Change password",
    changed: "Your password has been changed. Other devices have been logged out.",
    wrongCurrent: "The current password is not right.",
    tooShort: "The new password must have at least 12 characters.",
    tooLong: "The new password can have at most 128 characters.",
    mismatch: "The two new passwords are not the same.",
    same: "Please choose a password different from the temporary one.",
  },

  errors: { required: "Please fill in this field.", email: "Please enter a valid email address." },
  notFound: { title: "Not found", back: "Back to requests" },
};
